# path to sheet describing each cell.
cells: cells.tsv

# specify count table (rows: genes/transcripts/spikes, cols: cells)
counts:
  path: counts.tsv
  # define which kind of features are described in each row (must be a term understood by Ensembl biomart)
  feature_ids: hgnc_symbol

# Variables to use for batch effect removal and as factors to be ignored in variance
# analysis. This should always be the two cell cycle phases (G1, G2M) which are
# determined automatically during analysis. In addition, you may add any column
# name of the cell sheet (see above).
model:
  variables:
    - "G1"
    - "G2M"
  # Rely on spike-ins for variance model estimation.
  # This is usually not desired because of few and noisy spike-ins.
  # If this is set to false, engogeneous genes are used instead, under the
  # assumption that most of them are not differentially expressed.
  use-spikes: false
  # Minimum value of average difference in true (biological) log2 expression
  # between any two cells.
  min-bio-comp: 0.5
  # FDR threshold for selecting highly variable genes/transcripts (HVGs)
  fdr: 0.001
  # show the expression distribution of the top n HVGs
  show-n: 20
  # compute correlation for top n HVGs
  top-n: 200

# Comment in to assign cell type via signatures
celltype: 
  markers: resources/markers.tsv

diffexp:
  test-jun:
    # Refer to any colData from SingleCellExperiment here.
    # In addition, you can use celltype and detection_rate
    # (number of expressed genes in cell divided by total 
    # number of genes in experiment).
    design: "~ celltype + detection_rate"
    # Which coefficients of the model should be tested equal to zero.
    # E.g., 2 to test the first coefficient after the implicit intercept
    # (i.e., celltype in the example above).
    coef: 2
    # False discovery rate to control for.
    fdr: 0.05
    # Optional: constrain to cell types (comment out to use all cell types).
    celltypes:
      - IFNy+
      - IFNy-

species: human

spike-ins:
  pattern: "^ERCC"

filtering:
  min-avg-count: 10
