$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  counts:
    type: string

  cells:
    type: string

  species:
    enum:
      - mouse
      - human

  spike-ins:
    type: object
    properties:
      pattern:
        type: string
    required:
      - pattern

  filtering:
    type: object
    properties:
      min-avg-count:
        type: number
    required:
      - min-avg-count

  model:
    type: object
    properties:
      variables:
        type: array
        items:
          type: string
      use-spikes:
        type: boolean
    required:
      - use-spikes
      - variables

required:
  - species
  - spike-ins
  - filtering
  - model
  - cells
